[package]
name = "mealdb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.7.1"
serde = "1.0.126"
async-trait = "0.1.50"

[dependencies.reqwest]
features = ["json"]
version = "0.11.4"
