use serde::{Serialize, Deserialize};


#[allow(non_snake_case)]
/// API representation of a meal. non-snake case allowed since thats what the API returns...
#[derive(Serialize, Deserialize, Debug)]
pub(crate) struct _Meal {
    pub(crate) idMeal: String,
    pub(crate) strMeal: String,
    pub(crate) strCategory: String,
    pub(crate) strArea: String,
    pub(crate) strInstructions: String,
    pub(crate) strMealThumb: String,
    pub(crate) strTags: Option<String>,
    pub(crate) strYoutube: String,
    pub(crate) strIngredient1: String,
    pub(crate) strIngredient2: String,
    pub(crate) strIngredient3: String,
    pub(crate) strIngredient4: String,
    pub(crate) strIngredient5: String,
    pub(crate) strIngredient6: String,
    pub(crate) strIngredient7: String,
    pub(crate) strIngredient8: String,
    pub(crate) strIngredient9: String,
    pub(crate) strIngredient10: String,
    pub(crate) strIngredient11: String,
    pub(crate) strIngredient12: String,
    pub(crate) strIngredient13: String,
    pub(crate) strIngredient14: String,
    pub(crate) strIngredient15: String,
    pub(crate) strIngredient16: String,
    pub(crate) strIngredient17: String,
    pub(crate) strIngredient18: String,
    pub(crate) strIngredient19: String,
    pub(crate) strIngredient20: String,
    pub(crate) strMeasure1: String,
    pub(crate) strMeasure2: String,
    pub(crate) strMeasure3: String,
    pub(crate) strMeasure4: String,
    pub(crate) strMeasure5: String,
    pub(crate) strMeasure6: String,
    pub(crate) strMeasure7: String,
    pub(crate) strMeasure8: String,
    pub(crate) strMeasure9: String,
    pub(crate) strMeasure10: String,
    pub(crate) strMeasure11: String,
    pub(crate) strMeasure12: String,
    pub(crate) strMeasure13: String,
    pub(crate) strMeasure14: String,
    pub(crate) strMeasure15: String,
    pub(crate) strMeasure16: String,
    pub(crate) strMeasure17: String,
    pub(crate) strMeasure18: String,
    pub(crate) strMeasure19: String,
    pub(crate) strMeasure20: String,
    pub(crate) strSource: String,
    pub(crate) strImageSource: Option<String>,
    pub(crate) strCreativeCommonsConfirmed: Option<bool>,
    pub(crate) dateModified: Option<String>,
    pub(crate) strDrinkAlternate: Option<String>,

}
