pub(crate) mod area;
pub(crate) mod area_list_reponse;
pub(crate) mod categories;
pub(crate) mod categories_response;
pub(crate) mod ingredient;
pub(crate) mod ingredient_list_response;
/// API datamodel
pub(crate) mod meal;
pub(crate) mod meal_list_response;
